### ISSUE TITLE
Encryption key is not properly stored in session - resulting in data garbage when accessing files

### ISSUE THREAD

**Issue by tomte76** [owncloud/ios#246]
Since I upgraded my devices to iOS 8.1.1 I am not able to view PDF files downloaded with the iOS onwcloud client any more. The download works fine, the filesize seems to be ok, but nothing is displayed after the download is finished. If I try to open the file in Goodreader it is transfered to Goodreader but Goodreader says "PDF file format is not recognized". The filesize inside Goodreader is also ok. The same file works fine using the desktop sync client for Linux x64 and iOS Yosemite. I tried to reinstall the app but this didn't solve the problem. I can also download and view the files on the same iOS device using safari. If a can help to track down the issue please let me know.

**Comment by Derridaralalala** [comment]
@rperezb @javiergonzper just wondering if it was already submitted to the appstore? wish you all a great start in the new year and keep up the good work.

**Comment by rperezb** [comment]
ey @Derridaralalala we have been working in parallel on the iOS app and on the server side. 
Is it possible for you to update the server to the master version?
Thanks
Happy new year!

**Comment by tomte76** [comment]
Hi,

I can do an update. At the moment I'am using debian packages. Is it  
sufficient to check out the master branche of core from github an  
replace the corresponding directory tree from the package  
installation? Or can you provide information on what to do?

Quoting rperezb <notifications@github.com>:

**Comment by Derridaralalala** [comment]
@rperezb hey there. happy new year to you also! im not quiet sure what you mean by "master version"? do you mean the most recent one? which is as far as i understand 7.0.4 and that has been implemented since it came out...

**Comment by tomte76** [comment]
Hi,

will it also be ok to install the latest nighly debian package? That  
would be very easy and I could do it right away.

Quoting Daniel Tombeil <dt@admindu.de>:

**Comment by tomte76** [comment]
Hi,

as I found the owncloud nightly debian packages here

http://download.opensuse.org/repositories/isv:/ownCloud:/community:/nightly/Debian_7.0/ <http://download.opensuse.org/repositories/isv:/ownCloud:/community:/nightly/Debian_7.0/>

where not updates since may 2014 I downloaded the nightly tarball here

https://download.owncloud.org/community/daily/owncloud-daily-master.tar.bz2

and tried an upgrade to 8.0.0 alpha 2 with this code. In detail I unpacked the tarball an replaced the whole owncloud tree, afterwards I moved the config and the data-dir to the new tree an run 

php occ upgrade

The upgrade finished successfully after a while and I’am able to use the web-ui and the OS X desktop sync client. I also can use the iOS app on my iPhone and iPad without any problems by now. I rebooted the phone, used ownCloud, closed the app, start again and use it (download, local delete, re-download, update). I also rebooted the phone again an retried without any errors. I did the same on my ipad and it also worked fine. Uploading files does not work from iOS devices. The file appears e.g. in the web-ui but cannot be opened. The desktop client shows

“operation canceled” or “connection closed” 

in the logs. 

best regards

      Daniel=

**Comment by tomte76** [comment]
Content preview:  Uploading files does not work from the web-ui or the desktop
    ciient, too. Uploaded files appear in the listing in the web-ui and I can
    also see the encrypted file in the file-system on the server but if I try
    to access it the web-ui shows e.g. [...] 
 
 Content analysis details:   (-2.9 points, 5.0 required)
 
  pts rule name              description
 ---- ---------------------- --------------------------------------------------
 -1.0 ALL_TRUSTED            Passed through trusted hosts only via SMTP
 -1.9 BAYES_00               BODY: Bayes spam probability is 0 to 1%
                             [score: 0.0000]

Uploading files does not work from the web-ui or the desktop ciient, too. Uploaded files appear in the listing in the web-ui and I can also see the encrypted file in the file-system on the server but if I try to access it the web-ui shows e.g.

Unexpected server response (500) while retrieving PDF "https://cloud.admindu.de/owncloud/index.php/apps/files/ajax/download.php?dir=%2Fdocuments&files=doc8059.pdf”.

I cannot find corresponding error in the apache-logs. =

**Comment by tomte76** [comment]
Content preview:  Hi, I was able to track the upload issue down. It was a permissions
    problem inside the data-directory related to the files_encryption folder
   and its sub-folders. After fixing this everything works fine. No more problems
    with the iOS-App on upload, downloading or syncing files. Thank you for fixing
    this. Will this be backported to 7.x of if not what is the timeframe until
    the release of 8.x? [...] 
 
 Content analysis details:   (-2.9 points, 5.0 required)
 
  pts rule name              description
 ---- ---------------------- --------------------------------------------------
 -1.0 ALL_TRUSTED            Passed through trusted hosts only via SMTP
 -1.9 BAYES_00               BODY: Bayes spam probability is 0 to 1%
                             [score: 0.0000]

Hi,

I was able to track the upload issue down. It was a permissions problem inside the data-directory related to the files_encryption folder and its sub-folders. After fixing this everything works fine. No more problems with the iOS-App on upload, downloading or syncing files. Thank you for fixing this. Will this be backported to 7.x of if not what is the timeframe until the release of 8.x?

> Am 13.01.2015 um 00:58 schrieb Daniel Tombeil <daniel@tombeil.com>:
> 
> Uploading files does not work from the web-ui or the desktop ciient, too. Uploaded files appear in the listing in the web-ui and I can also see the encrypted file in the file-system on the server but if I try to access it the web-ui shows e.g.
> 
> Unexpected server response (500) while retrieving PDF "https://cloud.admindu.de/owncloud/index.php/apps/files/ajax/download.php?dir=%2Fdocuments&files=doc8059.pdf”.
> 
> I cannot find corresponding error in the apache-logs.

**Comment by chrsch** [comment]
Hi,
@tomte76 What was the actual permission problem - How can I fix this behavior as a workaround until it gets patched in a release? Is it as simple as chmod -R ??? oencloud/data/user/files_encryption? Thanks for feedback!
Chris

**Comment by tomte76** [comment]
Hi,

@chrsch. I did an upgrade to the nightly build by using the tarball. While copying the data-folder content to the new installation I messed up the permissions. So owncloud was not able to create the necessary folders in files_encryption therefore it could not store the key-files and it was not possible to download the files after the upload. I fixed it by doing a "chmod -R www-data:www-data" on the data-folder. The iOS problem was not fixed by the permissions but by upgrading to the latest nightly build tarball.

**Comment by chrsch** [comment]
Hi 
@tomte76 thanks for clarifying this, was already wondering why this should only effect the ios client but not any other ui ;-)
Chris

**Comment by redesigned** [comment]
I am having the same issue on a fresh ownCloud 7 install.  Turned on server side encryption, bought iOS app, all the test files are being delivered encrypted, cannot view any of them.  This is a fresh 7.0 install and a fresh install of the latest iOS app.  No other configuration changes made other then turning on server side encryption.

Any ideas how/when this will be fixed?

**Comment by Bewo** [comment]
Hi @redesigned 
the issue is fixed: #12917
And i think is fixed in ownCloud 8.0 RC2 too, but i have not tested yet.

**Comment by redesigned** [comment]
@Bewo So what do I have to do in order to have this fixed.  I'm on the latest stable public release of both ownCloud and the iOS app, do I have to install the release candidate of the upcoming version on my server?

**Comment by Bewo** [comment]
@redesigned 
Hi, there are two ways to do:
First one is the easiest: Wait for next week. There is the release scheduled for ownCloud 8.0 stable. There it should be fixed native.

Second way is: Change the code manually like its done in #12917 - works fine for me in daily use since three weeks.

**Comment by hellmachine2000** [comment]
So, for 4 months nothing happened regarding file previews and it is still not possible to use a feature that was there in the past. Makes the app mostly useless :-(    (IOS 8.1.3/iPhone6)
Any news about this?

**Comment by tflidd** [comment]
should be fixed in OC 8.0. As Bewo pointed out, you can apply the patch manually. For the 7.0.x-branch the fix has been rescheduled to 7.0.6: https://github.com/owncloud/core/pull/13496#issuecomment-73067432

**Comment by hellmachine2000** [comment]
Thanks for the hint. I upgraded to OC 8.0 and now the previews work again. Encryption seemingly had some bigger changes, resulting in the missing previews.

**Comment by hellmachine2000** [comment]
Well, upgraded to OC 8.0.2 and OC 3.4.1. for IOS, same problem again, this time previews not went gray, but black with an endless rotating preloader.
there was a time the app just worked :-(

**Comment by Bewo** [comment]
Hmm... I'm not able to reproduce the problem. Everything works perfect for me with OC 8.0.2 and iOS-OC-App 3.4.1 on iOS 8.2. Anything in your logs?

**Comment by rperezb** [comment]
This should be fixed within OC 8.0.2, if any of you may reproduce it, plese, reopen
