### ISSUE TITLE
[Sort by] As an iOS user I want to be able to decide whether data is shown by name or by date so that I find easily the files/folders

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#391]
AC:

  -  The order by default is alphabetical
  -  Include an option on the +, order
  -  When click on it, a menu is shown offering the user to decide what it´s the order to use
  -  This user story includes QA

(This is already included on Android: https://github.com/owncloud/android/pull/676)

**Comment by rperezb** [comment]
cc/ @jancborchardt is this ok for you to add this option under the + menu? thx

**Comment by jancborchardt** [comment]
The + button is strictly for adding new content, not akin to the Android dot-dot-dot menu. So no, we should not put it there. Check out how Dropbox does this for example – very nicely integrating it in the list next to the search bar (#17) which appears when you scroll up. We could add the sort toggle there even as long as we do not have the search bar.

Then secondly, the sorting choice should be by Name and Modified date (most recent first), just like on Android. _Not_ by size.

**Comment by gwes** [comment]
+1 for this feature.
In an enterprise environment and sort by date (ascending and descending) in particular would be handy.

Coding skills not so great but I'm happy to help test things

**Comment by danimo** [comment]
@rperezb What is required to make this happen?

**Comment by rperezb** [comment]
@danimo, priorities 

@MTRichards JFYI

**Comment by SamEliotFisher** [comment]
I'd like to propose to list all folders above the files. This is common in Windows explorer, Mac OS finder and nautilus.

**Comment by javiergonzper** [comment]
Yes @SamEliotFisher but if we do that we will have to remove the direct access to the letter or number that we have on the right.
If we implement your option should be an extra option. But I am not sure how to call it because it is not "alphabetically" and also it is not order "by type".

Order alphabetically
Order by type
Order by size
Order by ...

**Comment by nasli** [comment]
Related issue order by file/folder: #481

**Comment by javiergonzper** [comment]
Nice name :+1:

**Comment by SamEliotFisher** [comment]
Thanks @nasli for pointing out #481 again, indeed I did not see it before. @cherberg explained the issue very well. However, I agree with you @javiergonzper that this can be a optional.

**Comment by jancborchardt** [comment]
For simplicity reasons, initially there should be exactly 2 settings:
- Sort by name (this will sort A-Z, folders first)
- Sort by date (most recently modified first, files and folders mixed)

Anything else is not needed in the first iteration. We can still see about anything else after we have these basics down. Ah and of course the sort order should be remembered.

**Comment by rperezb** [comment]
done and released!
@danimo it happened! 💃  💃

**Comment by cherberg** [comment]
Unfortunately that does not solve the problem that I described:

The folders are still sorted among the files instead off at the top like I'm used from windows were I created this folder structure.

Unfortunately this still makes the IOS app useless for me.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, May 6, 2016 at 3:08 AM -0700, "Raquel Pérez Bartolomé" <notifications@github.com<mailto:notifications@github.com>> wrote:


done and released!
@danimo<https://github.com/danimo> it happened! ?? ??

-

**Comment by cherberg** [comment]
Addition:

Also I find the sorting different than from windows. Files and folders starting with numbers are sorted below files and folders with letters. This way my Folder ZZ Archive which I want at the bottom is the first in list above all other files which start with the create Date "20160513 Filename" and my Folders starting with numbers like "01 Private, 02 Work etc."

So the complete sorting is mixed up.

I have tried many 3rd party DAV Apps which all allow the sorting according to what I am used from windows. I am using "WebDAV Nav"
I simply don't understand why the owncloud app works differently.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, May 6, 2016 at 3:08 AM -0700, "Raquel Pérez Bartolomé" <notifications@github.com<mailto:notifications@github.com>> wrote:


done and released!
@danimo<https://github.com/danimo> it happened! ?? ??

-

**Comment by SamEliotFisher** [comment]
I know #481 has been put to backlog but I second that this is basics and should be supported. #,0-9 a-z. Folders before files.

**Comment by rperezb** [comment]
@cherberg yes the aim of this issue was not the change the way of ordering data (first folders and then files) the best for this request is to follow up on #481
